export const blogPosts = [
  {
    id: 1,
    title: "Your Access Database Isn't Dead — It Just Needs a Cloud Strategy",
    description:
      "Don't abandon your Microsoft Access database. Learn how to modernise it with cloud technologies like Azure SQL, SharePoint, and Power Platform while keeping your existing forms, reports, and business logic intact.",
    slug: "your-access-database-needs-a-cloud-strategy",
    date: "July 28, 2025",
    author: "Daniel Thomas",
    readingTime: "8 min",
    category: "Cloud Migration",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/cloud-strategy/plane.webp",
  },
  {
    id: 2,
    title:
      "Hybrid Access Solutions: Connect to Power Apps Without Losing What Works",
    description:
      "Learn how to modernise your Microsoft Access database with Power Platform without losing your existing forms, reports, and VBA code. Discover hybrid solutions that connect Access to Dataverse and Power Apps.",
    slug: "using-power-platform-with-access-database",
    date: "July 30, 2025",
    author: "Access Experts Team",
    readingTime: "14 min",
    category: "Dataverse",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/platform-database/resuscitate.webp",
  },
  {
    id: 3,
    title: "Microsoft Access vs. Excel: When to Use Which for Your Business",
    description:
      "Discover when to use Microsoft Access versus Excel for your Australian business data management. Learn the key differences, benefits, and how to leverage both tools together for optimal efficiency.",
    slug: "access-vs-excel",
    date: "October 23, 2025",
    author: "Daniel Thomas",
    readingTime: "12 min",
    category: "Excel",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/access-excel/access-vs-excel.webp",
  },
  {
    id: 4,
    title: "Why Dropbox Fails with Access Databases: Better Cloud Solutions",
    description:
      "Storing Microsoft Access databases in Dropbox leads to corruption, data loss, and conflicts. Learn why this approach fails and discover reliable alternatives like SQL Server and Azure SQL for secure multi-user access.",
    slug: "why-dropbox-fails-with-access-databases",
    date: "January 29, 2025",
    author: "Scott Robinson",
    readingTime: "7 min",
    category: "Database",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/dropbox/access-to-dropbox.webp",
  },
  {
    id: 5,
    title: "Your Access Database Just Hit 2GB... Now What? A Survival Guide",
    description:
      "The 2GB limit crisis hits without warning. Learn why it happens, how to recognize the warning signs, and discover immediate fixes vs long-term solutions including migration paths to SQL Server and Azure.",
    slug: "2gb-access-database-limit",
    date: "January 28, 2025",
    author: "Scott Robinson",
    readingTime: "15 min",
    category: "Database",
    featured: true,
    youtubeId: null,
    imagePath: "/blog/2gb/stop.webp",
  },
  {
    id: 6,
    title:
      "Access Database Running Slow? 7 Performance Killers (and How to Fix Them)",
    description:
      "Is your Access database painfully slow? Discover the 7 most common performance killers and learn quick fixes that can restore speed in minutes. Expert solutions for Australian businesses.",
    slug: "access-database-slow-performance",
    date: "January 30, 2025",
    author: "Scott Robinson",
    readingTime: "14 min",
    category: "Database",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/slow/performance.webp",
  },
  {
    id: 7,
    title:
      "Can You Run Microsoft Access on Mac? 5 Solutions That Actually Work",
    description:
      "Discover practical solutions for running Microsoft Access on Mac. Compare Parallels, cloud hosting, Boot Camp, file viewers, and migration alternatives to find the best option for your needs.",
    slug: "microsoft-access-on-mac",
    date: "December 17, 2025",
    author: "Scott Robinson",
    readingTime: "12 min",
    category: "Mac",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/mac/alternates.webp",
  },
  // {
  //   id: 8,
  //   title:
  //     "Microsoft Access Alternatives 2026: Choosing the Right Database Solution",
  //   description:
  //     "Considering alternatives to Microsoft Access? Our experts help you choose the RIGHT solution - SQL Server, Azure, Power Platform, or staying with Access. Honest comparison with real costs for Australian businesses.",
  //   slug: "https://www.accessexperts.com.au/blog/microsoft-access-alternatives-guide",
  //   date: "January 15, 2026",
  //   author: "Daniel Thomas",
  //   readingTime: "12 min",
  //   category: "Database",
  //   featured: true,
  //   youtubeId: null,
  //   imagePath: "/blog/alternatives/access-alternatives.webp",
  // },
];
